### ISSUE TITLE
remove Glitch and Sway

### ISSUE THREAD

**Issue by lassediercks** [filtercake/filtercake.github.io#10]
As you asked me for a11y feedback: 

I'd propose to remove the sway and glitch effect because to prevent epilepsy triggers and motion sickness.

**Comment by lassediercks** [comment]
I think this is the related reference https://www.w3.org/TR/WCAG20-TECHS/G19.html

**Comment by filtercake** [comment]
from the test section:

> - Check that there are no more than three flashes during any 1-second period.
> - If there are three flashes, check that the Light/Dark status at the end of the 1-second period is the same as at the start.

I read it this way: if i have 2 glitch animations running, this means that none of the two may have a duration < 0.66s so that there can never be more than 3 accumulated glitches per second. that is already the case.

besides, each glitch run leaves the element in the state it had before the animation, so no contrast changes.

i already changed the sway effect to running one single time, then leaving the content in that slightly rotated position.

same with the header image blend effect – runs one single time, very slowly, then stays that way.

this was really interesting to look into, thx a lot!
